name: Build images 🔧

on:
  pull_request:

jobs:
  get-old-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract versions
        run: |
          docker run --name framework ttl.sh/framework:main true || true
          docker cp framework:/framework/etc/kairos/versions.yaml versions_framework.old.yaml
          docker rm framework
          docker run --name framework_fips ttl.sh/framework_fips:main true || true
          docker cp framework_fips:/framework/etc/kairos/versions.yaml versions_fips.old.yaml
          docker rm framework_fips
      - uses: actions/upload-artifact@v3
        with:
          name: old_versions.zip
          path: |
            versions_framework.old.yaml
            versions_fips.old.yaml
  build-framework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ttl.sh/framework
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push framework
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: framework
      - name: Extract versions
        run: |
          docker run --name framework ${{ steps.meta.outputs.tags }} true || true
          docker cp framework:/framework/etc/kairos/versions.yaml versions_framework.new.yaml
          .github/yaml2md.sh >> $GITHUB_STEP_SUMMARY
          docker rm framework
      - uses: actions/upload-artifact@v3
        with:
          name: versions.zip
          path: |
            versions_framework.new.yaml
          if-no-files-found: error
  build-framework-fips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ttl.sh/framework_fips
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push framework
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: framework_fips
      - name: Extract versions
        run: |
          docker run --name framework ${{ steps.meta.outputs.tags }} true || true
          docker cp framework:/framework/etc/kairos/versions.yaml versions_fips.new.yaml
          .github/yaml2md.sh >> $GITHUB_STEP_SUMMARY
          docker rm framework
      - uses: actions/upload-artifact@v3
        with:
          name: versions_fips.zip
          path: |
            versions_fips.new.yaml
          if-no-files-found: error
  comment-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [build-framework, build-framework-fips, get-old-versions]
    steps:
      - uses: actions/checkout@v4
      - name: Download versions
        uses: actions/download-artifact@v3
        with:
          name: versions.zip
      - name: Download versions fips
        uses: actions/download-artifact@v3
        with:
          name: versions_fips.zip
      - name: Download old versions
        uses: actions/download-artifact@v3
        with:
          name: old_versions.zip
      - name: Generate PR text
        run: |
          .github/diffversions.sh
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
            comment_tag: bot-comment
            filePath: pr-message

