name: Release images 🔧

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build-framework:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit 
    with:
      security_profile: generic
  build-framework-fips:
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit 
    with:
      security_profile: fips