name: Release images 🔧

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write  # OIDC support
      contents: write
      security-events: write
    secrets: inherit 
    strategy:
      fail-fast: false
      matrix:
        security_profile: [generic, fips]
    uses: ./.github/workflows/reusable-build.yaml
    with:
      security_profile: ${{ matrix.security_profile }}